kind: SylvaWorkloadCluster
apiVersion: workloadclusteroperator.sylva/v1alpha1
metadata:
  name: my-wc-rke2-capo
  namespace: my-wc-rke2-capo
spec:
  k8sVersion: "1.28"
  infrastructure: openstack
  controlPlane:
    provider: rke2
    replicas: 1
  machineDeployments:
    my-md1-name:
      replicas: 1
  enabledUnits:
    multus: true
  clusterSettings:
    capo:
      ssh_key_name: management-node
      image_key: ubuntu-jammy-hardened-rke2-1-28-12
      network_id: 607511b1-295d-405f-a919-8ab76ebaf721
      flavor_name: "B1.large"
